const { db } = require('../database');

// All 254 Texas counties with FIPS codes and county seats
const texasCounties = [
  { name: "Anderson", seat: "Palestine", fips: "48001" },
  { name: "Andrews", seat: "Andrews", fips: "48003" },
  { name: "Angelina", seat: "Lufkin", fips: "48005" },
  { name: "Aransas", seat: "Rockport", fips: "48007" },
  { name: "Archer", seat: "Archer City", fips: "48009" },
  { name: "Armstrong", seat: "Claude", fips: "48011" },
  { name: "Atascosa", seat: "Jourdanton", fips: "48013" },
  { name: "Austin", seat: "Bellville", fips: "48015" },
  { name: "Bailey", seat: "Muleshoe", fips: "48017" },
  { name: "Bandera", seat: "Bandera", fips: "48019" },
  { name: "Bastrop", seat: "Bastrop", fips: "48021" },
  { name: "Baylor", seat: "Seymour", fips: "48023" },
  { name: "Bee", seat: "Beeville", fips: "48025" },
  { name: "Bell", seat: "Belton", fips: "48027" },
  { name: "Bexar", seat: "San Antonio", fips: "48029" },
  { name: "Blanco", seat: "Johnson City", fips: "48031" },
  { name: "Borden", seat: "Gail", fips: "48033" },
  { name: "Bosque", seat: "Meridian", fips: "48035" },
  { name: "Bowie", seat: "New Boston", fips: "48037" },
  { name: "Brazoria", seat: "Angleton", fips: "48039" },
  { name: "Brazos", seat: "Bryan", fips: "48041" },
  { name: "Brewster", seat: "Alpine", fips: "48043" },
  { name: "Briscoe", seat: "Silverton", fips: "48045" },
  { name: "Brooks", seat: "Falfurrias", fips: "48047" },
  { name: "Brown", seat: "Brownwood", fips: "48049" },
  { name: "Burleson", seat: "Caldwell", fips: "48051" },
  { name: "Burnet", seat: "Burnet", fips: "48053" },
  { name: "Caldwell", seat: "Lockhart", fips: "48055" },
  { name: "Calhoun", seat: "Port Lavaca", fips: "48057" },
  { name: "Callahan", seat: "Baird", fips: "48059" },
  { name: "Cameron", seat: "Brownsville", fips: "48061" },
  { name: "Camp", seat: "Pittsburg", fips: "48063" },
  { name: "Carson", seat: "Panhandle", fips: "48065" },
  { name: "Cass", seat: "Linden", fips: "48067" },
  { name: "Castro", seat: "Dimmitt", fips: "48069" },
  { name: "Chambers", seat: "Anahuac", fips: "48071" },
  { name: "Cherokee", seat: "Rusk", fips: "48073" },
  { name: "Childress", seat: "Childress", fips: "48075" },
  { name: "Clay", seat: "Henrietta", fips: "48077" },
  { name: "Cochran", seat: "Morton", fips: "48079" },
  { name: "Coke", seat: "Robert Lee", fips: "48081" },
  { name: "Coleman", seat: "Coleman", fips: "48083" },
  { name: "Collin", seat: "McKinney", fips: "48085" },
  { name: "Collingsworth", seat: "Wellington", fips: "48087" },
  { name: "Colorado", seat: "Columbus", fips: "48089" },
  { name: "Comal", seat: "New Braunfels", fips: "48091" },
  { name: "Comanche", seat: "Comanche", fips: "48093" },
  { name: "Concho", seat: "Paint Rock", fips: "48095" },
  { name: "Cooke", seat: "Gainesville", fips: "48097" },
  { name: "Coryell", seat: "Gatesville", fips: "48099" },
  { name: "Cottle", seat: "Paducah", fips: "48101" },
  { name: "Crane", seat: "Crane", fips: "48103" },
  { name: "Crockett", seat: "Ozona", fips: "48105" },
  { name: "Crosby", seat: "Crosbyton", fips: "48107" },
  { name: "Culberson", seat: "Van Horn", fips: "48109" },
  { name: "Dallam", seat: "Dalhart", fips: "48111" },
  { name: "Dallas", seat: "Dallas", fips: "48113" },
  { name: "Dawson", seat: "Lamesa", fips: "48115" },
  { name: "Deaf Smith", seat: "Hereford", fips: "48117" },
  { name: "Delta", seat: "Cooper", fips: "48119" },
  { name: "Denton", seat: "Denton", fips: "48121" },
  { name: "DeWitt", seat: "Cuero", fips: "48123" },
  { name: "Dickens", seat: "Dickens", fips: "48125" },
  { name: "Dimmit", seat: "Carrizo Springs", fips: "48127" },
  { name: "Donley", seat: "Clarendon", fips: "48129" },
  { name: "Duval", seat: "San Diego", fips: "48131" },
  { name: "Eastland", seat: "Eastland", fips: "48133" },
  { name: "Ector", seat: "Odessa", fips: "48135" },
  { name: "Edwards", seat: "Rocksprings", fips: "48137" },
  { name: "Ellis", seat: "Waxahachie", fips: "48139" },
  { name: "El Paso", seat: "El Paso", fips: "48141" },
  { name: "Erath", seat: "Stephenville", fips: "48143" },
  { name: "Falls", seat: "Marlin", fips: "48145" },
  { name: "Fannin", seat: "Bonham", fips: "48147" },
  { name: "Fayette", seat: "La Grange", fips: "48149" },
  { name: "Fisher", seat: "Roby", fips: "48151" },
  { name: "Floyd", seat: "Floydada", fips: "48153" },
  { name: "Foard", seat: "Crowell", fips: "48155" },
  { name: "Fort Bend", seat: "Richmond", fips: "48157" },
  { name: "Franklin", seat: "Mount Vernon", fips: "48159" },
  { name: "Freestone", seat: "Fairfield", fips: "48161" },
  { name: "Frio", seat: "Pearsall", fips: "48163" },
  { name: "Gaines", seat: "Seminole", fips: "48165" },
  { name: "Galveston", seat: "Galveston", fips: "48167" },
  { name: "Garza", seat: "Post", fips: "48169" },
  { name: "Gillespie", seat: "Fredericksburg", fips: "48171" },
  { name: "Glasscock", seat: "Garden City", fips: "48173" },
  { name: "Goliad", seat: "Goliad", fips: "48175" },
  { name: "Gonzales", seat: "Gonzales", fips: "48177" },
  { name: "Gray", seat: "Pampa", fips: "48179" },
  { name: "Grayson", seat: "Sherman", fips: "48181" },
  { name: "Gregg", seat: "Longview", fips: "48183" },
  { name: "Grimes", seat: "Anderson", fips: "48185" },
  { name: "Guadalupe", seat: "Seguin", fips: "48187" },
  { name: "Hale", seat: "Plainview", fips: "48189" },
  { name: "Hall", seat: "Memphis", fips: "48191" },
  { name: "Hamilton", seat: "Hamilton", fips: "48193" },
  { name: "Hansford", seat: "Spearman", fips: "48195" },
  { name: "Hardeman", seat: "Quanah", fips: "48197" },
  { name: "Hardin", seat: "Kountze", fips: "48199" },
  { name: "Harris", seat: "Houston", fips: "48201" },
  { name: "Harrison", seat: "Marshall", fips: "48203" },
  { name: "Hartley", seat: "Channing", fips: "48205" },
  { name: "Haskell", seat: "Haskell", fips: "48207" },
  { name: "Hays", seat: "San Marcos", fips: "48209" },
  { name: "Hemphill", seat: "Canadian", fips: "48211" },
  { name: "Henderson", seat: "Athens", fips: "48213" },
  { name: "Hidalgo", seat: "Edinburg", fips: "48215" },
  { name: "Hill", seat: "Hillsboro", fips: "48217" },
  { name: "Hockley", seat: "Levelland", fips: "48219" },
  { name: "Hood", seat: "Granbury", fips: "48221" },
  { name: "Hopkins", seat: "Sulphur Springs", fips: "48223" },
  { name: "Houston", seat: "Crockett", fips: "48225" },
  { name: "Howard", seat: "Big Spring", fips: "48227" },
  { name: "Hudspeth", seat: "Sierra Blanca", fips: "48229" },
  { name: "Hunt", seat: "Greenville", fips: "48231" },
  { name: "Hutchinson", seat: "Stinnett", fips: "48233" },
  { name: "Irion", seat: "Mertzon", fips: "48235" },
  { name: "Jack", seat: "Jacksboro", fips: "48237" },
  { name: "Jackson", seat: "Edna", fips: "48239" },
  { name: "Jasper", seat: "Jasper", fips: "48241" },
  { name: "Jeff Davis", seat: "Fort Davis", fips: "48243" },
  { name: "Jefferson", seat: "Beaumont", fips: "48245" },
  { name: "Jim Hogg", seat: "Hebbronville", fips: "48247" },
  { name: "Jim Wells", seat: "Alice", fips: "48249" },
  { name: "Johnson", seat: "Cleburne", fips: "48251" },
  { name: "Jones", seat: "Anson", fips: "48253" },
  { name: "Karnes", seat: "Karnes City", fips: "48255" },
  { name: "Kaufman", seat: "Kaufman", fips: "48257" },
  { name: "Kendall", seat: "Boerne", fips: "48259" },
  { name: "Kenedy", seat: "Sarita", fips: "48261" },
  { name: "Kent", seat: "Jayton", fips: "48263" },
  { name: "Kerr", seat: "Kerrville", fips: "48265" },
  { name: "Kimble", seat: "Junction", fips: "48267" },
  { name: "King", seat: "Guthrie", fips: "48269" },
  { name: "Kinney", seat: "Brackettville", fips: "48271" },
  { name: "Kleberg", seat: "Kingsville", fips: "48273" },
  { name: "Knox", seat: "Benjamin", fips: "48275" },
  { name: "Lamar", seat: "Paris", fips: "48277" },
  { name: "Lamb", seat: "Littlefield", fips: "48279" },
  { name: "Lampasas", seat: "Lampasas", fips: "48281" },
  { name: "La Salle", seat: "Cotulla", fips: "48283" },
  { name: "Lavaca", seat: "Hallettsville", fips: "48285" },
  { name: "Lee", seat: "Giddings", fips: "48287" },
  { name: "Leon", seat: "Centerville", fips: "48289" },
  { name: "Liberty", seat: "Liberty", fips: "48291" },
  { name: "Limestone", seat: "Groesbeck", fips: "48293" },
  { name: "Lipscomb", seat: "Lipscomb", fips: "48295" },
  { name: "Live Oak", seat: "George West", fips: "48297" },
  { name: "Llano", seat: "Llano", fips: "48299" },
  { name: "Loving", seat: "Mentone", fips: "48301" },
  { name: "Lubbock", seat: "Lubbock", fips: "48303" },
  { name: "Lynn", seat: "Tahoka", fips: "48305" },
  { name: "McCulloch", seat: "Brady", fips: "48307" },
  { name: "McLennan", seat: "Waco", fips: "48309" },
  { name: "McMullen", seat: "Tilden", fips: "48311" },
  { name: "Madison", seat: "Madisonville", fips: "48313" },
  { name: "Marion", seat: "Jefferson", fips: "48315" },
  { name: "Martin", seat: "Stanton", fips: "48317" },
  { name: "Mason", seat: "Mason", fips: "48319" },
  { name: "Matagorda", seat: "Bay City", fips: "48321" },
  { name: "Maverick", seat: "Eagle Pass", fips: "48323" },
  { name: "Medina", seat: "Hondo", fips: "48325" },
  { name: "Menard", seat: "Menard", fips: "48327" },
  { name: "Midland", seat: "Midland", fips: "48329" },
  { name: "Milam", seat: "Cameron", fips: "48331" },
  { name: "Mills", seat: "Goldthwaite", fips: "48333" },
  { name: "Mitchell", seat: "Colorado City", fips: "48335" },
  { name: "Montague", seat: "Montague", fips: "48337" },
  { name: "Montgomery", seat: "Conroe", fips: "48339" },
  { name: "Moore", seat: "Dumas", fips: "48341" },
  { name: "Morris", seat: "Daingerfield", fips: "48343" },
  { name: "Motley", seat: "Matador", fips: "48345" },
  { name: "Nacogdoches", seat: "Nacogdoches", fips: "48347" },
  { name: "Navarro", seat: "Corsicana", fips: "48349" },
  { name: "Newton", seat: "Newton", fips: "48351" },
  { name: "Nolan", seat: "Sweetwater", fips: "48353" },
  { name: "Nueces", seat: "Corpus Christi", fips: "48355" },
  { name: "Ochiltree", seat: "Perryton", fips: "48357" },
  { name: "Oldham", seat: "Vega", fips: "48359" },
  { name: "Orange", seat: "Orange", fips: "48361" },
  { name: "Palo Pinto", seat: "Palo Pinto", fips: "48363" },
  { name: "Panola", seat: "Carthage", fips: "48365" },
  { name: "Parker", seat: "Weatherford", fips: "48367" },
  { name: "Parmer", seat: "Farwell", fips: "48369" },
  { name: "Pecos", seat: "Fort Stockton", fips: "48371" },
  { name: "Polk", seat: "Livingston", fips: "48373" },
  { name: "Potter", seat: "Amarillo", fips: "48375" },
  { name: "Presidio", seat: "Marfa", fips: "48377" },
  { name: "Rains", seat: "Emory", fips: "48379" },
  { name: "Randall", seat: "Canyon", fips: "48381" },
  { name: "Reagan", seat: "Big Lake", fips: "48383" },
  { name: "Real", seat: "Leakey", fips: "48385" },
  { name: "Red River", seat: "Clarksville", fips: "48387" },
  { name: "Reeves", seat: "Pecos", fips: "48389" },
  { name: "Refugio", seat: "Refugio", fips: "48391" },
  { name: "Roberts", seat: "Miami", fips: "48393" },
  { name: "Robertson", seat: "Franklin", fips: "48395" },
  { name: "Rockwall", seat: "Rockwall", fips: "48397" },
  { name: "Runnels", seat: "Ballinger", fips: "48399" },
  { name: "Rusk", seat: "Henderson", fips: "48401" },
  { name: "Sabine", seat: "Hemphill", fips: "48403" },
  { name: "San Augustine", seat: "San Augustine", fips: "48405" },
  { name: "San Jacinto", seat: "Coldspring", fips: "48407" },
  { name: "San Patricio", seat: "Sinton", fips: "48409" },
  { name: "San Saba", seat: "San Saba", fips: "48411" },
  { name: "Schleicher", seat: "Eldorado", fips: "48413" },
  { name: "Scurry", seat: "Snyder", fips: "48415" },
  { name: "Shackelford", seat: "Albany", fips: "48417" },
  { name: "Shelby", seat: "Center", fips: "48419" },
  { name: "Sherman", seat: "Stratford", fips: "48421" },
  { name: "Smith", seat: "Tyler", fips: "48423" },
  { name: "Somervell", seat: "Glen Rose", fips: "48425" },
  { name: "Starr", seat: "Rio Grande City", fips: "48427" },
  { name: "Stephens", seat: "Breckenridge", fips: "48429" },
  { name: "Sterling", seat: "Sterling City", fips: "48431" },
  { name: "Stonewall", seat: "Aspermont", fips: "48433" },
  { name: "Sutton", seat: "Sonora", fips: "48435" },
  { name: "Swisher", seat: "Tulia", fips: "48437" },
  { name: "Tarrant", seat: "Fort Worth", fips: "48439" },
  { name: "Taylor", seat: "Abilene", fips: "48441" },
  { name: "Terrell", seat: "Sanderson", fips: "48443" },
  { name: "Terry", seat: "Brownfield", fips: "48445" },
  { name: "Throckmorton", seat: "Throckmorton", fips: "48447" },
  { name: "Titus", seat: "Mount Pleasant", fips: "48449" },
  { name: "Tom Green", seat: "San Angelo", fips: "48451" },
  { name: "Travis", seat: "Austin", fips: "48453" },
  { name: "Trinity", seat: "Groveton", fips: "48455" },
  { name: "Tyler", seat: "Woodville", fips: "48457" },
  { name: "Upshur", seat: "Gilmer", fips: "48459" },
  { name: "Upton", seat: "Rankin", fips: "48461" },
  { name: "Uvalde", seat: "Uvalde", fips: "48463" },
  { name: "Val Verde", seat: "Del Rio", fips: "48465" },
  { name: "Van Zandt", seat: "Canton", fips: "48467" },
  { name: "Victoria", seat: "Victoria", fips: "48469" },
  { name: "Walker", seat: "Huntsville", fips: "48471" },
  { name: "Waller", seat: "Hempstead", fips: "48473" },
  { name: "Ward", seat: "Monahans", fips: "48475" },
  { name: "Washington", seat: "Brenham", fips: "48477" },
  { name: "Webb", seat: "Laredo", fips: "48479" },
  { name: "Wharton", seat: "Wharton", fips: "48481" },
  { name: "Wheeler", seat: "Wheeler", fips: "48483" },
  { name: "Wichita", seat: "Wichita Falls", fips: "48485" },
  { name: "Wilbarger", seat: "Vernon", fips: "48487" },
  { name: "Willacy", seat: "Raymondville", fips: "48489" },
  { name: "Williamson", seat: "Georgetown", fips: "48491" },
  { name: "Wilson", seat: "Floresville", fips: "48493" },
  { name: "Winkler", seat: "Kermit", fips: "48495" },
  { name: "Wise", seat: "Decatur", fips: "48497" },
  { name: "Wood", seat: "Quitman", fips: "48499" },
  { name: "Yoakum", seat: "Plains", fips: "48501" },
  { name: "Young", seat: "Graham", fips: "48503" },
  { name: "Zapata", seat: "Zapata", fips: "48505" },
  { name: "Zavala", seat: "Crystal City", fips: "48507" }
];

function seedCounties() {
  console.log('Seeding Texas counties...');

  const insert = db.prepare(`
    INSERT INTO counties (name, seat, fips)
    VALUES (?, ?, ?)
    ON CONFLICT(name) DO NOTHING
  `);

  const insertMany = db.transaction((counties) => {
    for (const county of counties) {
      insert.run(county.name, county.seat, county.fips);
    }
  });

  try {
    insertMany(texasCounties);
    console.log(`✓ Successfully seeded ${texasCounties.length} Texas counties`);
    
    const count = db.prepare('SELECT COUNT(*) as count FROM counties').get();
    console.log(`Total counties in database: ${count.count}`);
  } catch (err) {
    console.error('Error seeding counties:', err.message);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  const { initDatabase } = require('../database');
  initDatabase();
  seedCounties();
  console.log('Seeding complete!');
}

module.exports = { seedCounties, texasCounties };
